### ISSUE TITLE
Dynamic parser - Promise handler

### ISSUE THREAD

**Issue by nickdelis** [poiw-org/saffron#62]
When we use promises (for example `.then()` ) scraper has been finished before the actual job.

**Comment by JexSrs** [comment]
This feature will have to wait for a while, because the code will need to be restructured. It will be implemented but not for the time being.

**Comment by JexSrs** [comment]
We will close this issue. Instead use:
```javascript
return new Promise((resolve, reject) => {
    resolve();
});
```
